name: pc
version: '22-0.1'
type: gadget
base: core22
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
confinement: strict
grade: devel
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    build-snaps: [snapd/latest/edge]
    stage-packages:
      - grub-efi-amd64-signed
      - grub-pc-bin
      - shim-signed
      - sbsigntool
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]

