name: xinyi-pc-classic
adopt-info: pc
type: gadget
base: core22
summary: Xinyi PC Classic gadget
description: |
    This gadget enables Xinyi PC Classic systems
confinement: strict
grade: stable

parts:
  pc:
    plugin: nil
    override-pull: |
      craftctl set version="$(snap info pc | sed -n 's|^  22/edge: *\(22-[0-9.]*\) *202.-.*|\1|p')"
    stage-snaps:
      - pc/22/stable
    stage:
      - -pc-boot.img
  cmdline:
    plugin: dump
    source: dump
