name: pc
version: '22-0.3'
type: gadget
base: core22
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
confinement: strict
grade: stable
icon: icon.png

parts:
  grub:
    source: .
    build-packages:
      - ubuntu-dev-tools
      - grub-common
    plugin: make

hooks:
  prepare-device:
    environment:
      # If you are forking and building your own gadget:
      # define your model's API key here
      # See https://ubuntu.com/core/services/guide/serial-vault-overview
      # for instructions on how to generate an API key
      # DO NOT check this API key into a publicly accessible VCS
      MODEL_APIKEY: ""
